# Generated by Django 3.1.2 on 2021-01-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='Score',
            new_name='best_score',
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='Username',
            new_name='username',
        ),
    ]
