# Generated by Django 3.1.2 on 2021-01-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210113_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='username',
            new_name='user',
        ),
    ]
