# Generated by Django 3.1.2 on 2021-01-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_apps_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='image_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
