# Generated by Django 3.1.2 on 2021-01-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryptdecrypt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedetails',
            old_name='action',
            new_name='selected_action',
        ),
    ]
