# Generated by Django 3.1.2 on 2021-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptdecrypt', '0002_auto_20210109_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='browsed_file',
            field=models.FileField(default=None, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(max_length=10),
        ),
    ]
